name: Passive Income Vault
favicon: null
layout_spectrum: 0.8076943613123149
typography_spectrum: 0.022381801391020417
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.9809728590771556
  lightness: 0.31288337311707437
  saturation: 0.5566185959614813
  rhythmicContrast: 0.023729055421426892
purpose: []
